-- Project currency and contract-native amounts. budgetUSD/allocatedUSD stay the USD rollup figures;
-- the *Native fields hold the number in the signed agreement and never move with the rate.
ALTER TABLE Project    ADD COLUMN currency        TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE Project    ADD COLUMN budgetNative    REAL NOT NULL DEFAULT 0;
ALTER TABLE BudgetLine ADD COLUMN allocatedNative REAL NOT NULL DEFAULT 0;
UPDATE Project SET currency='USD', budgetNative=10020.0 WHERE id='proj-trf';
UPDATE Project SET currency='EUR', budgetNative=22570.0 WHERE id='proj-fpu-vu';
UPDATE Project SET currency='USD', budgetNative=19932.0 WHERE id='proj-bwz-frl';
UPDATE Project SET currency='USD', budgetNative=8877.68 WHERE id='proj-asfari-2024';
UPDATE Project SET currency='EUR', budgetNative=19980.0 WHERE id='proj-fpu-icontent2';
UPDATE Project SET currency='USD', budgetNative=26000.0 WHERE id='proj-skf-invj';
UPDATE Project SET currency='USD', budgetNative=10000.0 WHERE id='proj-asfari-ler';
UPDATE Project SET currency='EUR', budgetNative=50895.0 WHERE id='proj-skf-mediamig';
UPDATE Project SET currency='USD', budgetNative=4000.0 WHERE id='proj-1785584153305';
UPDATE BudgetLine SET allocatedNative=1560.0 WHERE id='bl-1';
UPDATE BudgetLine SET allocatedNative=1200.0 WHERE id='bl-2';
UPDATE BudgetLine SET allocatedNative=1200.0 WHERE id='bl-3';
UPDATE BudgetLine SET allocatedNative=900.0 WHERE id='bl-4';
UPDATE BudgetLine SET allocatedNative=2800.0 WHERE id='bl-5';
UPDATE BudgetLine SET allocatedNative=800.0 WHERE id='bl-6';
UPDATE BudgetLine SET allocatedNative=600.0 WHERE id='bl-7';
UPDATE BudgetLine SET allocatedNative=360.0 WHERE id='bl-8';
UPDATE BudgetLine SET allocatedNative=600.0 WHERE id='bl-9';
UPDATE BudgetLine SET allocatedNative=1950.0 WHERE id='bl-fpu-1';
UPDATE BudgetLine SET allocatedNative=3000.0 WHERE id='bl-fpu-2';
UPDATE BudgetLine SET allocatedNative=1800.0 WHERE id='bl-fpu-3';
UPDATE BudgetLine SET allocatedNative=400.0 WHERE id='bl-fpu-4';
UPDATE BudgetLine SET allocatedNative=500.0 WHERE id='bl-fpu-5';
UPDATE BudgetLine SET allocatedNative=900.0 WHERE id='bl-fpu-6';
UPDATE BudgetLine SET allocatedNative=700.0 WHERE id='bl-fpu-7';
UPDATE BudgetLine SET allocatedNative=300.0 WHERE id='bl-fpu-8';
UPDATE BudgetLine SET allocatedNative=3000.0 WHERE id='bl-fpu-9';
UPDATE BudgetLine SET allocatedNative=1800.0 WHERE id='bl-fpu-10';
UPDATE BudgetLine SET allocatedNative=1200.0 WHERE id='bl-fpu-11';
UPDATE BudgetLine SET allocatedNative=800.0 WHERE id='bl-fpu-12';
UPDATE BudgetLine SET allocatedNative=500.0 WHERE id='bl-fpu-13';
UPDATE BudgetLine SET allocatedNative=5000.0 WHERE id='bl-fpu-14';
UPDATE BudgetLine SET allocatedNative=720.0 WHERE id='bl-fpu-15';
UPDATE BudgetLine SET allocatedNative=2650.0 WHERE id='bl-ler-a1';
UPDATE BudgetLine SET allocatedNative=1250.0 WHERE id='bl-ler-a2';
UPDATE BudgetLine SET allocatedNative=640.0 WHERE id='bl-ler-a3';
UPDATE BudgetLine SET allocatedNative=310.0 WHERE id='bl-ler-a4';
UPDATE BudgetLine SET allocatedNative=150.0 WHERE id='bl-ler-a5';
UPDATE BudgetLine SET allocatedNative=9000.0 WHERE id='bl-mm-1';
UPDATE BudgetLine SET allocatedNative=18000.0 WHERE id='bl-mm-2';
UPDATE BudgetLine SET allocatedNative=13500.0 WHERE id='bl-mm-3';
UPDATE BudgetLine SET allocatedNative=4500.0 WHERE id='bl-mm-4';
UPDATE BudgetLine SET allocatedNative=5895.0 WHERE id='bl-mm-5';
UPDATE BudgetLine SET allocatedNative=12500.0 WHERE id='bl-inv-1';
UPDATE BudgetLine SET allocatedNative=6700.0 WHERE id='bl-inv-2';
UPDATE BudgetLine SET allocatedNative=2500.0 WHERE id='bl-inv-3';
UPDATE BudgetLine SET allocatedNative=2000.0 WHERE id='bl-inv-4';
UPDATE BudgetLine SET allocatedNative=2300.0 WHERE id='bl-inv-5';
UPDATE BudgetLine SET allocatedNative=1800.0 WHERE id='bl-ic2-11';
UPDATE BudgetLine SET allocatedNative=2000.0 WHERE id='bl-ic2-12';
UPDATE BudgetLine SET allocatedNative=1000.0 WHERE id='bl-ic2-13';
UPDATE BudgetLine SET allocatedNative=1400.0 WHERE id='bl-ic2-14';
UPDATE BudgetLine SET allocatedNative=800.0 WHERE id='bl-ic2-15';
UPDATE BudgetLine SET allocatedNative=1000.0 WHERE id='bl-ic2-31';
UPDATE BudgetLine SET allocatedNative=1200.0 WHERE id='bl-ic2-41';
UPDATE BudgetLine SET allocatedNative=600.0 WHERE id='bl-ic2-42';
UPDATE BudgetLine SET allocatedNative=1200.0 WHERE id='bl-ic2-43';
UPDATE BudgetLine SET allocatedNative=240.0 WHERE id='bl-ic2-44';
UPDATE BudgetLine SET allocatedNative=1440.0 WHERE id='bl-ic2-51';
UPDATE BudgetLine SET allocatedNative=1440.0 WHERE id='bl-ic2-52';
UPDATE BudgetLine SET allocatedNative=960.0 WHERE id='bl-ic2-53';
UPDATE BudgetLine SET allocatedNative=2400.0 WHERE id='bl-ic2-61';
UPDATE BudgetLine SET allocatedNative=2000.0 WHERE id='bl-ic2-62';
UPDATE BudgetLine SET allocatedNative=500.0 WHERE id='bl-ic2-63';
UPDATE BudgetLine SET allocatedNative=5000.0 WHERE id='bl-bwz-a';
UPDATE BudgetLine SET allocatedNative=13120.0 WHERE id='bl-bwz-b';
UPDATE BudgetLine SET allocatedNative=1812.0 WHERE id='bl-bwz-oh';
UPDATE BudgetLine SET allocatedNative=4000.0 WHERE id='bl-mada-01';
UPDATE BudgetLine SET allocatedNative=2500.0 WHERE id='bl-ler-a6';
